INSERT INTO orders (
  menu_items,   -- ARRAY OF ARRAYS [[1,2,3],[2,3,4]] -> [[item_id, qnty, unit_price]]
  item_names,
  customer_name ,
  customer_phone ,
  total_paid ,
  start_time ,
  end_time
)
VALUES
('$1-js-a' , '$2-js-a' , $3, $4 , '$5-js-a', '$6-js-a','$7-js-a'); -- -js-a = js automated, meaning the value that goes there will be generated by js from the client input form plus...